Version: "3:

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      # n8n basic config
      N8N_PORT: 5678
      N8N_HOST: 0.0.0.0
      N8N_PROTOCOL: http
      GENERIC_TIMEZONE: Asia/Kolkata
      TZ: Asia/Kolkata

      # REQUIRED â€“ keep this safe
      N8N_ENCRYPTION_KEY: 129c12370bbe24eca59db757bf23c2ee411617bfdb5129d2216f669acdb88405
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_RUNNERS_ENABLED: true
      N8N_SECURE_COOKIE: false

    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
